### ISSUE TITLE
No IE support

### ISSUE THREAD

**Issue by dkrasniy** [frappe/charts#102]
Charts not showing in IE 11. Empty white box in place of chart.

**Comment by system19** [comment]
With IE 11 having been released 4 years ago and with virtually no users []( http://gs.statcounter.com) maybe its not worth catering for?

**Comment by wopian** [comment]
IE11 (unfortunately) still has over 3% browser share (more than Firefox)

**Comment by andriijas** [comment]
you can use another charting library if you need IE support. I like that it doesnt support IE, keep it small and modern.

**Comment by pratu16x7** [comment]
While I agree with @system19 and @andriijas, I'm not very experienced with browser support and do feel sad about this. But there just seems no way to do it other than using a polyfill. https://github.com/frappe/charts/pull/16

**Comment by pratu16x7** [comment]
@dkrasniy I notice you use Bootstrap over at https://github.com/middlebury/frontend/issues/126 and need percentage charts. Those are pretty easy to do with Bootstrap progress bars ;)
