### ISSUE TITLE
Pie chart display issue.

### ISSUE THREAD

**Issue by vampuke** [frappe/charts#108]
#### Expected Behaviour
Pie chart was expected as a circle.
#### Actual Behaviour
Pie chart will be out of shape when one of the values is over 50%.
#### Steps to Reproduce:
*

NOTE: Add a GIF/Screenshot if required.
![2018-01-02 16 20 13](https://user-images.githubusercontent.com/25778349/34477973-f4a6e8ce-efd8-11e7-9852-d059ef2c9d76.png)
Frappé Charts version:
v0.0.7

**Comment by achillesrasquinha** [comment]
@sheweichun

**Comment by kevinjqiu** [comment]
Here's a minimal reproducible example: http://jsfiddle.net/rwq87jd7/

**Comment by dackom** [comment]
Any solutions for this? :-/

**Comment by hugofabricio** [comment]
Solution for pie chart?

**Comment by ricardo-marino** [comment]
This hotfix should be sufficient. It worked for me. I haven't check the other visualizations, but they should not be affected.

**Comment by thomas-oo** [comment]
@achillesrasquinha could you look into @ricardo-marino's PR for this issue? #152

**Comment by danielhasan1** [comment]
it's still not working rendering problem is still there. the problem occurs when there is a bigger value in a set of values.

**Comment by sanketh-nm** [comment]
> it's still not working rendering problem is still there. the problem occurs when there is a bigger value in a set of values.

That is because #181 is not yet merged. However, you can just apply the fix yourself by looking at the code changes from [this commit ](https://github.com/ricardo-marino/charts/commit/228684865b819f8f6d94678416b960f3046ca003)
