### ISSUE TITLE
chart image data url

### ISSUE THREAD

**Issue by agreif** [frappe/charts#130]
Hi,
is it possible to get the data url in the form of "data:image/png;base64,..." ?

thanks

**Comment by pratu16x7** [comment]
Could you guide on how to do that?

We could try to derive the SVG data of the chart, that would have a much more portable and have a smaller file size. It is partially possible now, full support would involve incorporating the CSS styles as well, which is a bit tricky.

**Comment by agreif** [comment]
I only know that a canvas has a toDataURL method that can deliver dieimage contents in different types. But with SVG I have no clue. sorry
