### ISSUE TITLE
[v.1.0.0] Release 

### ISSUE THREAD

**Issue by pratu16x7** [frappe/charts#132]
Following up on #93. Some new features (as listed at https://frappe.github.io/charts) include:
- Mixed type axis datasets
- Stacked bar charts
- Value over data points
- Y Markers and regions
- Dot size, Bar space size, and other options
- Legend for axis charts

The X axis is static, unlike the scaled Y axis. We'll incorporate time scaling soon :) 

#### API Change
`Chart` options no longer incorporate the `parent`, it is instead the first parameter passed in creation, `options` being second:
```js
const chart = new Chart("#chart", { // or a DOM element
    title: "My Awesome Chart",
    data: data,
    type: 'bar',
    height: 250,
    colors: ['#7cd6fd', '#743ee2']
})
```

As this was a rewrite, I'll be now looking to incorporate existing PRs and issues in the meantime.

**Comment by t47io** [comment]
Could you put this into a `CHANGELOG`?

**Comment by t47io** [comment]
Also the demo is out-of-date in terms of `datasets` shape, it takes `name` now instead of `label`.

**Comment by mpetrs** [comment]
I'm also struggling with API changes:

```
Uncaught TypeError: Cannot read property 'specific_values' of undefined
    at e (frappe-charts.min.iife.js:1)
    at e.i (frappe-charts.min.iife.js:1)
    at new e (frappe-charts.min.iife.js:1)
    at F (frappe-charts.min.iife.js:1)
    at new t (frappe-charts.min.iife.js:1)
```

**Comment by agritheory** [comment]
The `name` vs `label` are both poor namespace choices; I think it should be `legend`. Oh well.

**Comment by renatodeleao** [comment]
following along, when doing `axis-mixed` charts, on datasets,  chart type definition is no longer defined by `type: 'bar'` but with `chartType: 'bar'`.

**Comment by NetOperatorWibby** [comment]
Has anyone figured out how to get a simple bar chart rendered? I've been wrangling with this for the past few hours, only because I like that this chart plugin doesn't have dependencies...but it also doesn't work. Maybe there's too many things in flux.

**Comment by pratu16x7** [comment]
@NetOperatorWibby 

Just included a Code Pen demo over at https://frappe.github.io/charts/
Let me know if that helps. :)

**Comment by NetOperatorWibby** [comment]
@pratu16x7 Thanks for that, it was really helpful. I've since moved on to using Chartist because I needed something immediately. I may come back to Frappe in the future.
