### ISSUE TITLE
request: add a delete/purge/dispose method

### ISSUE THREAD

**Issue by guidorice** [frappe/charts#144]
I am using frappe-charts with a vdom library (mithril) and when a component gets re-created, the previous frappe-chart instance leaves some event handlers in place, e.g. window resize. 

I skimmed through the source code, but didn't see any delete or purge or dispose methods. (maybe I am overlooking?)

PS thanks for this great library!

**Comment by andreasvirkus** [comment]
That event does not seem to work properly with multiple charts. Relevant: https://github.com/frappe/charts/issues/168, https://github.com/frappe/charts/issues/174, https://github.com/frappe/charts/issues/97#issuecomment-383278099
