### ISSUE TITLE
No `parent` element to render on was provided.

### ISSUE THREAD

**Issue by chintan9** [frappe/charts#148]
#### Expected Behaviour

should render the chart 

#### Actual Behaviour

gives error 

#### Steps to Reproduce:
*
use this url https://jsbin.com/cafuhezosu/1/edit?html,js,output

No `parent` element to render on was provided.

NOTE: Add a GIF/Screenshot if required.
https://jsbin.com/cafuhezosu/1/edit?html,js,output

Frappé Charts version:
v1.0.0

**Comment by ucffool** [comment]
Not a bug, you just aren't listening to the error. :)
Missing the div with an ID of **chart**.
[https://jsbin.com/caxuvapepa/1/edit?html,js,output](https://jsbin.com/caxuvapepa/1/edit?html,js,output)
CLOSED.

**Comment by chintan9** [comment]
thanks

**Comment by niftylettuce** [comment]
Ref: https://github.com/frappe/charts/issues/199#issuecomment-642374110

**Comment by niftylettuce** [comment]
This is most definitely a bug.  Please re-open.

**Comment by Gubbu77** [comment]
Error: No `parent` element to render on was provided.
Same Issue, Please Re-Open @himynameisdave
