### ISSUE TITLE
v1.1 Webpack import doesn't work

### ISSUE THREAD

**Issue by ucffool** [frappe/charts#155]
#### Expected Behaviour
[v1.0 fiddle](https://jsfiddle.net/7s560fsz/8/)
#### Actual Behaviour
[v1.1 fiddle](https://jsfiddle.net/rbygtg62/3/)
#### Steps to Reproduce:
Using unpkg (confirmed 1.1 is loading)

Frappé Charts version:
1.1

**Comment by guidorice** [comment]
I am using the ES6 module, and I had to change my import from this:
`import Chart from 'frappe-charts/dist/frappe-charts.min.esm';`
to this
`import { Chart } from 'frappe-charts';`

to get my chart working. Not sure, but maybe it is related to what you are seeing? it seems like the bundling changed in 1.0 -> 1.1

**Comment by pratu16x7** [comment]
@guidorice @ucffool looks like unpkg takes time to update?

**Comment by ucffool** [comment]
Well it took about 30 minutes after you pushed v1.1 for it to appear on unpkg, but since then the file has been live on that site.
I'm not an expert on npm or unpkg, but [the files are different](https://www.diffchecker.com/EQNPa5in).

**Comment by pratu16x7** [comment]
Looks like the file is currently updated on both jsdeliver and unpkg.

**Comment by ucffool** [comment]
> Looks like the file is currently updated on both jsdeliver and unpkg.

Yes, but if you look at the fiddles, **it still isn't working**.
```ReferenceError: Chart is not defined```

**Comment by pratu16x7** [comment]
@ucffool 
Okay, my bad. We've recently enabled [selective imports](https://github.com/frappe/charts/pull/137) in the bundling that allows you to import individual components in Charts (AxisChart, PieChart, or simply Chart and so on). For that, the overall object that's exported contains all of them, and it is by default called `frappe`, so in the browser scenario where imports aren't involved, we'll have to use them as `frappe.Chart()`. Updated docs for the same. Pity about the incomprehensiveness though.

Thanks for reporting.

**Comment by t47io** [comment]
Does not seem to work with `webpack`; `import { Chart } from 'frappe-charts';` returns `undefined`

**Comment by pratu16x7** [comment]
@t47io Any possible fix for this?

**Comment by pratu16x7** [comment]
@t47io Any possible fix for this? If there isn't, we'll still need to update the usage instructions with the `import { Chart } from 'frappe-charts/dist/frappe-charts.esm.js';` workaround.

**Comment by t47io** [comment]
I believe this line should be removed: https://github.com/frappe/charts/blob/master/package.json#L8 Whoever uses it directly in browser (e.g. `<script src="https://unpkg.com/frappe-charts@1.1.0/dist/frappe-charts.min.iife.js"></script>`) does not seem to consult `package.json` anyway.  `webpack` however defaults to `browser` as said in https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by itslenny** [comment]
If you're using typescript a quick fix is to add this to your tsconfig.json. This fixed it for me leaving here incase someone else needs it.

```
"paths": {
      "frappe-charts": [
        "node_modules/frappe-charts/dist/frappe-charts.esm.js"
      ]
}
```
