### ISSUE TITLE
Chart causing side effects in Single Page Application

### ISSUE THREAD

**Issue by anishdcruz** [frappe/charts#168]
#### Expected Behaviour

The chart should not cause side effects when its removed from page.

#### Actual Behaviour
I am using Vue.js and Vue router to make Single Page Application.

The chart is emitting events even when its removed from the page.

Is there a way to forcefully remove global event listeners created by chart?

<img width="800" alt="screen shot 2018-05-03 at 1 00 34 pm" src="https://user-images.githubusercontent.com/2182620/39570865-60da20da-4ed2-11e8-9115-4ebb998475ca.png">

<img width="1274" alt="screen shot 2018-05-03 at 1 00 50 pm" src="https://user-images.githubusercontent.com/2182620/39570868-610a27ee-4ed2-11e8-9011-88f791ca0d6f.png">

Thank you for your hard work!

**Comment by hugofabricio** [comment]
Solved?

**Comment by andreasvirkus** [comment]
Seeing the same thing in my Vue app on other routes after loading a Frappe chart in a previous route.
I was hoping this would solve it, but the errors still appear on every resize.
```
  beforeDestroy () {
    this.teamGraph.unbindWindowEvents()
    this.reviewerGraph.unbindWindowEvents()
  }
```

**Comment by scmmishra** [comment]
Fixed: https://github.com/frappe/charts/pull/238
