### ISSUE TITLE
How to place Y axis on the right side?

### ISSUE THREAD

**Issue by limonte** [frappe/charts#170]
Is it possible to achieve something like this:

![image](https://user-images.githubusercontent.com/6059356/39646453-293e4846-4fe4-11e8-97de-a69fde6d5d85.png)

**Comment by limonte** [comment]
Any response?

**Comment by travisNeel** [comment]
I am by no means an expert, but I was able to achieve these results in the `make_y_axis()` function by passing  `true` to `get_y_axis_line_props()`. Hope this helps.
