### ISSUE TITLE
Presence of zero values deforms pie charts 

### ISSUE THREAD

**Issue by massimo-cassandro** [frappe/charts#173]
#### Actual Behaviour
![schermata 2018-05-08 alle 14 09 55](https://user-images.githubusercontent.com/1047169/39756465-0edad51c-52ca-11e8-94a8-c2dd5eb8f3dc.png)

#### Steps to Reproduce:
```
{
	"height": 350,
	"title": "Fatturati: confronto Network (apr 2018)",
	"type": "pie",
	"colors": ["#7ED321", "#007bff", "#fc0", "#FDA5EE", "#9c6d1e", "#c7b6f7"],
	"data": {
		"labels": ["Blunet", "Bluvacanze", "Cisalpina Tours", "Primarete Viaggi e Vacanze", "Travelbuy", "Uniposte"],
		"datasets": [{
			"name": "apr 2018",
			"values": [5270381, 0, 0, 3249212, 1033141, 377]
		}]
	}
}
```

Frappé Charts version: 1.1.0 (iife)

**Comment by Eyewritecode** [comment]
I'm having the same issue but with small values!! 😞 
<img width="549" alt="screen shot 2018-05-17 at 12 37 54" src="https://user-images.githubusercontent.com/5019653/40172620-77fd9410-59cf-11e8-926e-8a8541aea8d5.png">

**Comment by kedar9444** [comment]
@eyewritecode : its not due to the small values. the graph behaves unpredictable when you have values subtotal less that 100.

**Comment by scmmishra** [comment]
Fixed: https://github.com/frappe/charts/pull/181
