### ISSUE TITLE
long axis labels are cut off

### ISSUE THREAD

**Issue by massimo-cassandro** [frappe/charts#175]
#### Expected Behaviour
labels width should respect text width

#### Actual Behaviour
long numbers are cut off

#### Steps to Reproduce:
Build a chart width high values

![schermata_2018-05-11_alle_14_40_12](https://user-images.githubusercontent.com/1047169/39924864-c6f49708-5529-11e8-91dd-d94d9d4946c4.png)

Frappé Charts version: 1.1.0

**Comment by scmmishra** [comment]
Fixed this.

Added an option that will allow you to shorten these labels. `10000` will be shortened to `10 K` and so on for larger numbers. This is disabled by default. To enable this use the `shortenYAxisNumbers` option in `axisOptions` when configuring your chart. You can refer the following example.

https://github.com/frappe/charts/blob/d69b3780d9f425b295843f6a30cae721a5805f71/docs/assets/js/demoConfig.js#L21-L37
