### ISSUE TITLE
How to set heatmap width to expand and fill the whole div

### ISSUE THREAD

**Issue by Eyewritecode** [frappe/charts#176]
I'm using the heatmap chart and want it to fill the parent's width. 

- I've set the div's width to 100% but nothing changed.
- Set the width option of frappe, again nothing changed.

Frappé Charts version: 1.1.0

**Comment by qgustavor** [comment]
[*What did you see?!*](https://xkcd.com/979/)

**Comment by switz** [comment]
Also running into this -- my chart seems fixed at 752px width.
