### ISSUE TITLE
Need to some inputs to start contributing to this project

### ISSUE THREAD

**Issue by saiprakash1** [frappe/charts#18]
I am a kind of newbee here and looking to contribute to any open source projects, just as way to keep learning new things. I have cloned this project and when i run npm run dev on my machine, i see the below error. Could some one please let me know where iam going wrong

 303:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

 303 problems (303 errors, 0 warnings)
 303 errors, 0 warnings potentially fixable with the `--fix` option.

**Comment by achillesrasquinha** [comment]
Apologies, we're working on issue and contribution guidelines soon. Just look at the space for any update.

**Comment by schnelleyoga** [comment]
I am also new here, nice to meet you)

**Comment by scmmishra** [comment]
Closing dormant thread
