### ISSUE TITLE
Stacked bar chart not drawing

### ISSUE THREAD

**Issue by Mashiane** [frappe/charts#187]
#### Expected Behaviour
A stacked bar chart should draw

#### Actual Behaviour
A grouped bar chart is drawn

#### Steps to Reproduce:
Here is a codepen: https://codepen.io/anele-mash-mbanga/pen/xzWGPb

NOTE: Add a GIF/Screenshot if required.

Frappé Charts version:
1.1

**Comment by scmmishra** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/18097732/85991621-53b80280-ba11-11ea-948d-4094d67c85bb.png">


in your code pen demo, you have defined `barOptions` twice (line 12 and 29)
