### ISSUE TITLE
Scatter seems to be broken

### ISSUE THREAD

**Issue by agritheory** [frappe/charts#188]
#### Expected Behaviour
Scatter chart type shows lots of dots on an X/Y axis

#### Actual Behaviour

![image](https://user-images.githubusercontent.com/18033666/42120102-7f828b1a-7be3-11e8-92ca-26779949b491.png)

#### Steps to Reproduce:
Change [this code pen](https://codepen.io/pratu16x7/pen/wjKBoq) to scatter. It will fail when any dataset is set to scatter. If the main type is set to scatter, it's worse:

![image](https://user-images.githubusercontent.com/18033666/42120121-cf4380e6-7be3-11e8-96fb-e4dbbc506aed.png)

Frappé Charts version:
V1.1.0

**Comment by scmmishra** [comment]
Scatter is not a chart type available yet. Probably was in the roadmap then, but is not implemented
