### ISSUE TITLE
Issue in generating a graph for analytics for  ERPnext non profit module

### ISSUE THREAD

**Issue by RajahuliRahul** [frappe/charts#190]
#### Expected Behaviour
A graph should be generated to display the anaytics in the erpnext non profit module to keep track of the donor's donations and health report .
#### Actual Behaviour

![screenshot from 2018-07-23 18-02-01](https://user-images.githubusercontent.com/28565811/43137005-1c98b4b4-8f68-11e8-8331-3475959b1974.png)

#### Steps to Reproduce:
*

NOTE: Add a GIF/Screenshot if required.
``
Frappé Charts version:1.1.0

**Comment by scmmishra** [comment]
Seems like this issue belongs to ERPNext. I am closing the issue for now as there is no particular problem that is mentioned.
