### ISSUE TITLE
Frappe Chart Not Rendering immediately

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/charts#191]
#### Expected Behaviour
Frappe chart renders immediately and automatically without further intervention upon loading the page.

#### Actual Behaviour
Container is loaded, but graph is not rendered. Some items like pop up elements of the graph are rendered, but the underlying graph is not visible. Once user resizes the window, the graph renders completely and functions normally.

#### Steps to Reproduce:
*Enter the URL of the page or doctype containing a frappe chart
*Press ENTER
* Wait for the items to finish loading.  Result will be evident.
* Now resize the window, you should see the graph properly render in front of your eyes.

### [Code used in .js page:](https://gist.github.com/Tropicalrambler/c63231acce8e4b1e3308363bfb1354e3)

NOTE: Add a GIF/Screenshot if required.
![qulvpnb8nv](https://user-images.githubusercontent.com/16600935/43220787-27691884-9008-11e8-83f0-0946eb44caea.gif)

Frappé Charts version:
v1.0.0 or more?

**Comment by DevenK** [comment]
I’ve found a workaround and that is to add a draw in a timeout under where you create the chart as follows:

```
// existing code
const chart = new frappeChart.Chart(dedicated_div, options)
// add
setTimeout(function () {chart.draw(!0)}, 1);
```

**Comment by Tropicalrambler** [comment]
https://discuss.erpnext.com/t/frappe-chart-in-erpnext-on-new-page/32544/10
