### ISSUE TITLE
Doughnut 

### ISSUE THREAD

**Issue by larizzatg** [frappe/charts#196]
Is there a way to use  a doughnut chart in this library?

**Comment by atilkan** [comment]
nope. These are the charts.
<img width="271" alt="screen shot 2018-09-20 at 10 58 18" src="https://user-images.githubusercontent.com/1254613/45804193-1a8f2200-bcc4-11e8-9ce6-a9088e92662a.png">

**Comment by ratnajeetshyamkunwar** [comment]
@pratu16x7  creating a PR to solve this issue [https://github.com/frappe/charts/pull/221](url)
