### ISSUE TITLE
'Chart is not a constructor' when importing as ES6 module

### ISSUE THREAD

**Issue by maulerjan** [frappe/charts#199]
After installing as a npm module (`npm install frappe-charts`), I'm unable to import a constructor.

Docs says to import like this:
```
import {Chart} from 'frappe-charts'
```
...the docs from NPM says to import like this:
```
import Chart from 'frappe-charts/dist/frappe-charts.min.esm'
```

Either way it doesn't work for me.
```
const chart = new Chart(this.chartWrapper, {...})
```
results in `*.Chart is not a constructor` error.

I'm using Webpack 4 and React 16 (but React shouldn't have anything to do with this issue).

Frappé Charts version:
v1.1.0

Any suggestions?
Thanks!

**Comment by panjizhi** [comment]
same here

**Comment by deligent-ant** [comment]
same here

**Comment by andreasvirkus** [comment]
You need to import the EcmaScript module straight from the dist folder:
```
import { Chart } from 'frappe-charts/dist/frappe-charts.esm.js'
```

cc @deligent-ant @maulerjan @panjizhi

**Comment by GrosSacASac** [comment]
Ps: After update I use import
`import {Chart} from "../node_modules/frappe-charts/dist/frappe-charts.min.esm.js";`

**Comment by Sugamm** [comment]
@andreasvirkus It works for me but now it is showing a different error.
 
`Error: No `parent` element to render on was provided`

**Comment by andreasvirkus** [comment]
How are you initialising the graph?

**Comment by himynameisdave** [comment]
I'm having a similar issue in my [`svelte-frappe-charts`](https://github.com/himynameisdave/svelte-frappe-charts/issues/12) repo. It's very unclear why it isn't working, and I want to rule out Svelte itself, but it seems to be a similar `Error: No parent element to render on was provided` issue.

**Comment by niftylettuce** [comment]
@himynameisdave @andreasvirkus @Sugamm I too had the same issue, but resolved it by defining the element outside of options:

```js
const $el = document.querySelector('#frost-chart');
const chart = new Chart($el, {
  data: {
```

**Comment by niftylettuce** [comment]
I've switched to use https://github.com/apexcharts/apexcharts.js and https://github.com/gionkunz/chartist-js as this project seems to be abandoned and unmaintained per #293.

**Comment by scmmishra** [comment]
Hey @niftylettuce sorry you had a bad experience with frappe-charts.

Charts enjoys a niche in small projects and many devs love it from the simplicity. Apex charts is a great library. I still maintain Frappe Charts, however not full time, The larger focus of our small team is on Frappe Framework and ERPNext. 

There is a major version overhaul in the pipeline which solves a lot of problems. I would love for you to give it a try once it's released.

**Comment by scmmishra** [comment]
```
import { Chart } from "frappe-charts/dist/frappe-charts.esm.js";

```

Is the

**Comment by himynameisdave** [comment]
@scmmishra in the next major version, will there just be a hybrid import which combines ESM/CommonJS (like most NPM packages), so that users can just do:

```
// In ESM environments:
import { Chart } from 'frappe-charts';

// In CJS environments:
const { Chart } = require('frappe-charts');
```

This would be great, so that developers don't need to worry about digging into the `/dist/` folder to find the file that they need.

**Comment by scmmishra** [comment]
> @scmmishra in the next major version, will there just be a hybrid import which combines ESM/CommonJS (like most NPM packages)? This way users can just do:
> 
> ```js
> // In ESM environments:
> import { Chart } from 'frappe-charts';
> 
> // In CJS environments:
> const { Chart } = require('frappe-charts');
> ```
> 
> This would be great, so that developers don't need to worry about digging into the `/dist/` folder to find the file that they need.
> 
> 

Yess, this will make life simpler for all of us. I'll have this implemented soon.

Thanks

**Comment by himynameisdave** [comment]
@scmmishra that's great news, thank you!

**Comment by himynameisdave** [comment]
Any movement on this issue? Users are still experiencing this downsteam in [`svelte-frappe-charts`](https://github.com/himynameisdave/svelte-frappe-charts/issues/32).

The issue is that users are setting their bundlers to [look for `browser` build files](https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser), which will break because there is no `Chart` exported in the `iffe` bundle.

I think the "correct" way to solve this is to produce a `umd` build to use for `browser` environments. That should be "universal" and should work when users include `frappe-charts` as a script, as well as for those importing the library with a bundler via CJS/ESM modules.

I am happy to take a stab at fixing this.
