### ISSUE TITLE
[Feature Request] Add Typescript typedefinitions

### ISSUE THREAD

**Issue by rajshrimohanks** [frappe/charts#2]
It would be great if this has native support for Angular by bringing in type definitions.

Kudos for a cool library 👍 

EDIT: To make it more clear, I'm not asking for Angular wrappers. Just type-definitions, which would let me use the library without `declare`-ing constants all over the place in Typescript and killing the whole purpose of using Typescript. And as @harunurhan has mentioned below, it's also great for documentation as I can simply look up the definition file to know if a method or parameter is required.

**Comment by achillesrasquinha** [comment]
I think the primary goal of the author was to stick with zero dependencies. You could still go ahead and create a wrapper for other view libs.

**Comment by icholy** [comment]
@achillesrasquinha you misunderstood the request. @rajshrimohanks is requesting type definitions, not an angular wrapper.

**Comment by harunurhan** [comment]
Adding definition files will at least give your public api methods/classes some documentation.

**Comment by achillesrasquinha** [comment]
Okay, my bad. We're not much into Angular, but we'd love you to send in a PR and maybe provide support for what you say.

The primary intention of this lib was to be integrated with github.com/frappe/erpnext
Never felt the use for it.

**Comment by rajshrimohanks** [comment]
@achillesrasquinha Thanks. Let me see if I can do it over the weekend.

**Comment by pspeter3** [comment]
@rajshrimohanks would you like help?

**Comment by rajshrimohanks** [comment]
@pspeter3 Would be great if you can. :) I've never written types for a third party library before, so it would be a while before I can figure out how to go about it.

**Comment by pspeter3** [comment]
I can take a first crack at the PR and perhaps you can review for correctness?

**Comment by rajshrimohanks** [comment]
@pspeter3 Would be glad to do so. :)

**Comment by achillesrasquinha** [comment]
Looking forward! 🎉  We just had @tobiaslins try a React example for the lib.

**Comment by achillesrasquinha** [comment]
Hello, any update on this? Closing otherwise. Feel free to reopen.
