### ISSUE TITLE
0 valuse in stacked bar

### ISSUE THREAD

**Issue by deligent-ant** [frappe/charts#201]
0 value in stacked bar
even the data is 0 ,therr is alao a line over the bay 
![image](https://user-images.githubusercontent.com/30307406/47416373-2630a580-d7a8-11e8-99cf-98ff8c67f36b.png)

**Comment by deligent-ant** [comment]
const MIN_BAR_PERCENT_HEIGHT = 0   把这个值改成0就可以了

**Comment by scmmishra** [comment]
Fixed here: https://github.com/frappe/charts/pull/209
