### ISSUE TITLE
Multiple Charts event listeners not removed

### ISSUE THREAD

**Issue by zeidanbm** [frappe/charts#210]
#### Expected Behaviour
Seems there is an issue with multiple charts defined with a virtual dom library on spa applications. 
`unbindWindowEvents()` method should remove all frappe charts events(resize, orientationchange). I'm aware we can not detect current events but there should be a better way of implementing this behaviour or maybe i should implement it in a different way in my vue js app...

##### Other Related issues:
#200 , #168 , #144 , #174 , #97 
Those might be related but they don't discuss multi charts, the solution in them will not work here

#### Actual Behaviour
Inspecting with the browser reveals that there is two resize and orientationchange events being added on initial load (as we have 2 charts in my example). So, when trying to use unbindWindowEvents() on both, it only removes one of the events and the other won't be removed. Also, upon route chage the event keeps incrementing so it will be left with 2 on next visit and so on.
Issue seems to occure with chrome, however firefox doesn't throw errors, eventhough it's keeping one of the events active.

#### Steps to Reproduce:
Use this codepen on Chrome browser to see what exactly is happening on route changes. [codpen link](https://codepen.io/zeidanbm/pen/qLmzqG)

1. Navigate to the other page
2. open console log
3. resize the window

###Frappé Charts version:
1.1.0

###Google Chrome Version :
69.0.3497.100 (Official Build) (64-bit)

###Firefox Version:
64.0

###OS:
Ubuntu 16.04 LTS

**Comment by scmmishra** [comment]
Fixed here: https://github.com/frappe/charts/pull/238
