### ISSUE TITLE
Remove chart

### ISSUE THREAD

**Issue by tabuna** [frappe/charts#212]
I thank you for your work, but I ran into a problem: 

I use the chart on the SPA website and I need to destroy the chart (after going to another page),
because if I don’t follow this, I will receive a lot of errors:

```
Error: <rect> attribute x: Expected length, "NaN"
Error: <rect> attribute width: Expected length, "NaN".
```

And so every time the page changes in size.

Any support would be helpful.

**Comment by scmmishra** [comment]
I have made a fix for this, https://github.com/frappe/charts/commit/92674f94f19e4c784d501125f7c454e246f9d1b9

I'm closing the issue, however you can reopen it if you still face problems

**Comment by tabuna** [comment]
Wow thank you
