### ISSUE TITLE
How can I set stroke weight for lines?

### ISSUE THREAD

**Issue by ssuess** [frappe/charts#226]
I am using vue2-frappe to wrap frappe, and for some reason lines are not showing on my line charts. I can tell in dev tools source that that path is there, but for some reason the stroke weight is set to 0. Is there a config option for setting stroke weight?

**Comment by ssuess** [comment]
although this is not the best way, I found that modifying the stroke-weight 0 var inside of `frappe-charts.min.esm.js` works for now...

**Comment by ghord** [comment]
Same issue. It seems that option lineOptions.hideLine and als lineOptions.areaFill are not working on 1.2.0

**Comment by ghord** [comment]
As a workaround I've added following css to my site.

```css
.line-graph-path {
    stroke-width: 2px !important;
}
```

**Comment by rmehta** [comment]
Fixed with 1.2.2
