### ISSUE TITLE
Repo's contributing guidelines not at parity with https://bit.ly/2WC7K1x

### ISSUE THREAD

**Issue by tmrietz** [frappe/charts#228]
Contributing guidelines on GitHub repo should reflect those on project's site, or point to those instead. There are other details on the project's site at https://bit.ly/2WC7K1x that aren't present in the repo's readme

**Comment by scmmishra** [comment]
Fixed: https://github.com/frappe/charts/commit/87684777c6284241f80ba71dd9e8f4a1ebd2fe58
