### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [frappe/charts#230]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/frappe/charts/blob/master/package.json#L48

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by scmmishra** [comment]
Thanks for informing about this. I have removed this module and will be making a release soon.
