### ISSUE TITLE
Donut chart display issue

### ISSUE THREAD

**Issue by JoaoHL** [frappe/charts#233]
#### Expected Behaviour

![Rounded, proportional chart](https://user-images.githubusercontent.com/5323327/61246643-b8594f00-a725-11e9-9985-9d232950b546.png)

#### Actual Behaviour

Well-rounded donut char for any data proportion: 
![Not rounded donut chart](https://user-images.githubusercontent.com/5323327/61246603-98299000-a725-11e9-8717-916447241c9a.png)

#### Steps to Reproduce:

1 - Create a HTML file with a div with class "frappe-div"
2 - import frappe minified JS script
3 - create a script tag within the file with the following script, after the Frappe Chart import:

```
new frappe.Chart( ".frappe-div", { // or DOM element
			data: {
				labels: ["A", "B", "C", "D"],

				datasets: [
					{
						values: [29, 19, 2, 2]
					}
				],

			},

			type: 'donut', // or 'bar', 'line', 'pie', 'percentage', 'donut'
			height: 300,
			colors: ['#0A3771', '#1157B4', '#156DE1']

		});
```

Frappé Charts version:
Probably 1.2.3. I downloaded the package on 3rd July.

**Comment by scmmishra** [comment]
Hi, I have fixed the issue (commit: https://github.com/frappe/charts/commit/e4117952ddd7b90ccd45b8fe9a8289f332d4e646) 

It will be released soon.

**Comment by JoaoHL** [comment]
Very thanks!
