### ISSUE TITLE
Can this be used in ERPNext

### ISSUE THREAD

**Issue by asoral** [frappe/charts#254]
I am sorry if I am using the wrong portal for requesting an explanation but I coudn't find the community page for such things.

I work in ERPNext and want a way to be able to merge this into the existing chart functionality in it. For example. when I select a"Toggle Chart, the pop-up shows the list of all the chart types (like bar, stacked bar, mixed, etc) and based on the chart type the option should change and visualized post clicking and reviewing the preview.

**Comment by scmmishra** [comment]
It's already used in Frappe Framework and in by extension in ERPNext as well. I'm closing this issue as it's not related to the development of Frappe Charts in itself. Perhaps open it in Frappe Repo or ask on discuss.erpnext.com
