### ISSUE TITLE
ReferenceError: document is not defined.

### ISSUE THREAD

**Issue by vaibhavgavade** [frappe/charts#257]
Here is my code
import {Chart} from 'frappe-charts/dist/frappe-charts.min.cjs'
data = {
    labels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    datasets: [
        { values: [18, 40, 30, 35, 8, 52, 17, -4] }
    ]
}

const DemoChart=new Chart( "#chart", {
    data: data,
    type: 'bar',
    height: 140,
    colors: ['red']
});

export default DemoChart

**Comment by scmmishra** [comment]
You need to give me more details. In general, you need to wait for [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event) before creating the chart.
