### ISSUE TITLE
Heatmap not respecting time zones

### ISSUE THREAD

**Issue by iDemonix** [frappe/charts#26]
If I have the following data:

```
heatmap_data[1490313600.0] = 4; // Friday, 24 March 2017 00:00:00 GMT
heatmap_data[1490400000.0] = 7; // Saturday, 25 March 2017 00:00:00 GMT
heatmap_data[1490486400.0] = 3; // Sunday, 26 March 2017 00:00:00 GMT (UK timezone +1 at 1am)
heatmap_data[1490572800.0] = 6; // Monday, 27 March 2017 00:00:00 GMT
```
In the UK, the timezone changed from GMT to GMT+1 on the 26th of March (at 1am). If my data is stored in UTC/Epoch, the day after the 26th is +86400 of the 26th's timestamp.

I added some logging:

```
let timestamp = Math.floor((current_date.getTime()/1000)).toFixed(1);
console.log(timestamp);
```

which gives:

```
1490400000.0
1490486400.0
1490569200.0 // 3600 difference
```

Not sure if this is a bug or a feature request, but ideally I'd like to present all my data in UTC (as that's how it is stored), and then have the graphing library deal with timezone/date issues. I'm pulling from graphite using its `summarize()` function which returns data at UTC midnight for each day, I'd need a wrapper to tweak the data if this library couldn't handle it for me.

Also, your example on the homepage doesn't work for the heatmap, I believe it's because (after reading the source) the timestamp has to be at midnight for the given day? (this is why the above time zone thing seems to be an issue)

**Comment by iDemonix** [comment]
I appended a line and got it working:

```
let timestamp = Math.floor((current_date.getTime()/1000)).toFixed(1);
timestamp = Math.floor(timestamp - (timestamp % 86400)).toFixed(1); // appended
```

**Comment by pratu16x7** [comment]
@iDemonix Fixed in latest build. Thanks!
