### ISSUE TITLE
Use css instead of scss

### ISSUE THREAD

**Issue by mobop** [frappe/charts#267]

**Comment by wopian** [comment]
Sass is a devDependency that never sees production and keeps the CSS much simpler while working on it.

**Comment by mobop** [comment]
Not a good decision

**Comment by ddiss** [comment]
I think plain CSS would make sense here too - frappe doesn't need much in the way scss features, and it's already nicely self-contained / dependency free.

**Comment by lucasdcrk** [comment]
I think SCSS should almost always be the way to go to avoid repetitive code.
