### ISSUE TITLE
isValidColor failing on rgb() statements

### ISSUE THREAD

**Issue by MeFisto94** [frappe/charts#274]
#### Expected Behaviour
Specifying `(\w*)rgb(255, 255, 0)` and `(\w*)rgba(255, 255, 0, 255)` as color should work.

#### Actual Behaviour
`" rgb(255, 255, 0)" is not a valid color.`,
caused by:
```javascript
function isValidColor(string) {
  // https://stackoverflow.com/a/8027444/6495043
  return /(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i.test(string);
}
```

#### Steps to Reproduce:
* `colors: [ ' rgb(255, 255, 0)']`
* alternatively: `colors: [getComputedStyle(document.documentElement).getPropertyValue('--primary-color')]`

In my case I was accessing a precomputed css-variable color which has been defined using rgb, otherwise working around this issue would be more easy.

Frappé Charts version: 1.3.0

Edit: Additionally, `isValidColor` is case sensitive.

**Comment by Thunderbottom** [comment]
should be fixed with #275

**Comment by MeFisto94** [comment]
Nit: this does not account for leading whitespaces before rgb, right?
I'm mentioning this because the above example `getComputedStyle().getPropertyValue` will output `    rgb()` depending on the css, see this:

```css
test.test {
   color1: rgb(0, 0, 0);
   color2:rgb(255, 255, 255);
}
```

Here `getPropertyValue('color1')` returns ` rgb(0, 0, 0);` where `getPropertyValue('color2')`  returns `rgb(255, 255, 255);`.

It is a philoshopical question whether the caller should trim the values they pass or whether the library should accept spaced rgb's, though. I'd be fine with both.

**Comment by Thunderbottom** [comment]
should be handled now.

**Comment by MeFisto94** [comment]
Thanks, that's perfect :)
