### ISSUE TITLE
Use JSDoc

### ISSUE THREAD

**Issue by nainardev** [frappe/charts#280]
This project has types?
If no, atleast add JSDoc

**Comment by scmmishra** [comment]
Right now, the code quality is not the best. As far as documentation is concerned, the docs at frappe.io/charts have significant coverage.

**Comment by nainardev** [comment]
JSDoc or TypeScript declerations - which is easier to do?

**Comment by scmmishra** [comment]
JSDoc is preferable. A large part of getting this done is first including the documentation comments to the codebase in general. 

All the documentation right now resides on [frappe.io](https://frappe.io/charts/docs) and I'm planning to keep it there.  I'm not sure how far will JSDoc as a tool will work for that, can we generate markdown on the fly?
That way we can have a GitHub action that will generate the documentation and send a PR to the documentation repo?
Do you think this will work?

The priority right now is for the codebase to be documented extensively even if it stays in comments within the codebase for that matter.
