### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by niftylettuce** [frappe/charts#293]
Let me know, would love to help.  96 open issues and 14 PR's, plus major issues like this one: <https://github.com/frappe/charts/issues/199>.

I am also the owner of the `frappe` package!

**Comment by ollyboy** [comment]
Would like to know if abandoned as well. Have spent a lot of time to try get this to work in frappe, issues logged here, definatly not yet ready for production

**Comment by niftylettuce** [comment]
I switched to apexcharts https://apexcharts.com/

**Comment by ollyboy** [comment]
hey dont close this, give them a chance to repond

**Comment by ollyboy** [comment]
here is another team switching from charts https://github.com/fusioncms/fusioncms/issues/374
