### ISSUE TITLE
How do you change the chart type at runtime ?

### ISSUE THREAD

**Issue by The-Bright-Lord** [frappe/charts#296]
I want to be able to do something like in this demo
![image](https://user-images.githubusercontent.com/13927773/87214260-aca86480-c348-11ea-986b-cd612ae42c95.png)

But I want to do it without recreating the chart object every time.
So far I have tried doing : (Assuming initially the chart was a bar graph)

`chart.type = 'donut'`
`chart.draw(true)`

Does not seem to work. Is there any API to do this? Also, many api's that are talked about in the Issues section are not available in the docs.

One more thing. Is there any way to change the font-size of the labels and the title in the chart?

**Comment by The-Bright-Lord** [comment]
As for the font-size issue, figured it out

`chart.measures.titleFontSize = 18;`
`chart.draw(true);`

Many of these things are not documented int the official documentation.
As for the first question. I am still stuck

**Comment by scmmishra** [comment]
`chart.draw(true)` is run when redrawing the chart when the size of the container is changed. Before this a lot of preprocessing is done. I'd suggest you to delete the old chart object and redraw it.

The way it's done in the demo can be found [here](https://github.com/frappe/frappe_io/blob/master/frappe_io/public/docs/charts.js) and [here](https://github.com/frappe/frappe_io/blob/master/frappe_io/public/lib/demoBuilder.js)

We have a Vue app that replaces the chart every time we trigger any action. There is [charts-playground](https://playground.shivam.dev/) a WIP demo for charts. There too we replace the chart as is. 

There is no computation cost to this as the preprocessing has to be done anyway. Also, the rendering is pretty fast so the change won't be noticed even for relatively large datasets.

P.S. The vue app was written two years ago and is highly specific for the website demo.

**Comment by The-Bright-Lord** [comment]
@scmmishra 

Isn't it taxing for large datasets to recreate the chart everytime ? Also, Is the method of changing the font-size okay? I have to set-it again everytime I change the chart. Is there any way you can expose the `BASE_MEASURES` and other constants for the user to modify before the chart is created?

I guess the basic settings such as font size, family etc should be left to the user. Also, there is no interaction for pie and donut charts. I ended up extending the `Chart` object with jQuery and adding the function similar to `bindLabels` in order to get it to work. 

Is this something that is planned for V2.0 ? If so what is the timeline for it? I really like Frappe and would like to use it instead of the clanky Charts.js

**Comment by scmmishra** [comment]
The two major computational tasks including preprocessing the data and calculating svg values.

The data operations are mostly array operations which is optimised really well by browsers. The svg calculations also are array operations by and large, but instead of simple aggregation like done for the data, it's a bit more complex but still can take advantage of speculative optimization strategies used by Chrome and Firefox. 

I've had dataset with about 500 points rendering almost instantly, so, I believe this shouldn't be a problem.

These operations will have to be done if  dynamically changing the graph types was allowed.

About changing the title font styles, at the moment it's not supported. The title is also svg text, what I recommend is to not add any title, instead just add the title separately outside the container. In Frappe and ERPNext and other places we use charts without title.

You can still change things via css overrides. With the new version perhaps we can have better deafult styles along with more customisation options in case someone does not want to conform to the default opinions

About the pie charts and donuts, the interactivity is hover at the moment, I'm not sure if they have a click event yet, I'll have to verify. Can you elaborate on that more?

Regarding Charts v2, we are overhauling our branding slowly, I'll put out a roadmap soon. Perhaps by the end of August we'll have v2 available generally.

**Comment by The-Bright-Lord** [comment]
Yeah, the Pie and the donut charts support only hover for the moment. Not click. I wanted the page to navigate to a detailed view when they click on a slice.

This is what I am doing at the moment. My JS is not great. I am a noob. But well, I do what I can.


        $.extend(chart, {

                setSelectedEventHandler(func) {

                    var title_current = "";

                    this.container.addEventListener("mousemove", (e) => {

                        const target = e.target;
                        let slices = this.components.get('donutSlices').store;
                        if (slices.includes(target)) {
                            let i = slices.indexOf(target);
                            let title = (this.formatted_labels && this.formatted_labels.length > 0
                                ? this.formatted_labels[i] : this.state.labels[i]);

                            title_current = title;
                        }

                    });

                    this.container.addEventListener("click", (e) => { func(title_current); });
                }

            });

            chart.setSelectedEventHandler((title) => { console.log(title); });

I hoped that the data-selected event would just work for the **AggregateCharts** as well.

I also wanted to ask you, how much of Frappe charts supports IE at the moment ? Or does it even?. Can we make it work with any polyfills? 

As for charts V2. That is great!. Hope most of the customizations and events for all chart types makes it to V2. Great work BTW !.

**Comment by scmmishra** [comment]
> Yeah, the Pie and the donut charts support only hover for the moment ... I hoped that the data-selected event would just work for the AggregateCharts as well.

I'll add this to v2 roadmap!

> I also wanted to ask you, how much of Frappe charts supports IE at the moment

I haven't tried it on IE. A good guess would say it works fairly well on IE 9 and above. However, animations are done through [SMIL](https://www.w3.org/TR/REC-smil/) which is [not supported by IE](https://caniuse.com/#feat=xhtmlsmil)

> Hope most of the customizations and events for all chart types makes it to V2

Yes, hoping to make things more extensible, especially overriding defaults. Allowing customizations is a slippery slope, however it's understandable the most folks don't want to conform to the default opinions.

The new defaults are expected to be more modern, most folks will love the defaults.

For instance this is how percentage chart may look like 

![image](https://user-images.githubusercontent.com/18097732/87679059-58164680-c799-11ea-9b5f-33c398171039.png)

This is a mock image

**Comment by The-Bright-Lord** [comment]
@scmmishra 

I Do have a bug report. Why does a chart with 3 labels and dataset as `1,0,0` in barchart do this ?

![image](https://user-images.githubusercontent.com/13927773/87787007-9161bb80-c858-11ea-8d73-e34d7976c6b2.png)

There is no vertical bar for "Windows". Also there is no y-axis legend. But this is perfectly fine with an aggregate chart

![image](https://user-images.githubusercontent.com/13927773/87787094-b6562e80-c858-11ea-9945-df22afbc77ab.png)

**Comment by scmmishra** [comment]
@The-Bright-Lord I have created a separate issue for this. Can we discuss it in that thread? https://github.com/frappe/charts/issues/298

**Comment by The-Bright-Lord** [comment]
@scmmishra  Sure.
