### ISSUE TITLE
[Feature request] Realtime data

### ISSUE THREAD

**Issue by abacaj** [frappe/charts#31]
Is there anyway to use the current api to display realtime streaming data, say append a value to the end and remove a value from the beginning?

**Comment by pratu16x7** [comment]
@abacaj  `add_data_point()` and `remove_data_point()` do take in an index (and a datapoint in case of adding), so can be used to achieve what you suggest

![screen shot 2017-11-04 at 4 01 39 pm](https://user-images.githubusercontent.com/5196925/32404649-b1d61228-c179-11e7-8b2b-cf61e3f7466a.png)

**Comment by pratu16x7** [comment]
@abacaj Let us know how that works out for you, feel free to reopen in case it doesn't :)
