### ISSUE TITLE
Show the zero in the tooltip, if the dataset contains zero values

### ISSUE THREAD

**Issue by manassolanki** [frappe/charts#32]
#### Expected Behaviour
Should show zero

#### Actual Behaviour
![image](https://user-images.githubusercontent.com/20757311/32377613-3dc6b096-c0ce-11e7-9f2b-c857e95becdf.png)

**Comment by pratu16x7** [comment]
@manassolanki 
Yep, that is intended :) No bar for zero is easy to make out if surrounded by non zero bars (as in the above screen), but for a series of zero values it makes difficult to figure out the positions. Ref the same in Spotify for example:

![screen shot 2017-06-26 at 4 06 08 pm](https://user-images.githubusercontent.com/5196925/32385247-845f0ebc-c0e3-11e7-9ebb-dbbabca9dadd.png)

**Comment by manassolanki** [comment]
@pratu16x7  Sorry, Created the issue in hurry without proper heading 😜 
Contributed the fix with my first PR
