### ISSUE TITLE
Fix #315 causes exception when name not provided

### ISSUE THREAD

**Issue by jmrossy** [frappe/charts#320]
#### Expected Behaviour

No exception when name is left null/undefined

#### Actual Behaviour

Exception is thrown.
The issue is with this line which was modified in the last release:
https://github.com/frappe/charts/pull/315/files#diff-5fae7e3027fe415c8929935437f5b31e266fddc2b776cd2df8210f4f51f3512fR113

#### Steps to Reproduce:
* Create a chart with a dataset that has no name
* Exception is thrown due to attempt to call replace on undefined 

Frappé Charts version: v1.5.5

**Comment by scmmishra** [comment]
Released a fix for this https://github.com/frappe/charts/releases/tag/v1.5.6
