### ISSUE TITLE
Accessibility issue: default text colors are low-contrast

### ISSUE THREAD

**Issue by mathiasbynens** [frappe/charts#324]
The default text colors used by frappe-charts for axis labels have insufficient contrast. Here’s [an example from the docs](https://frappe.io/charts/docs/basic/annotations#regions):

![](https://user-images.githubusercontent.com/81942/104443316-9482fd80-5596-11eb-9b1d-1712f9638cc6.png)

The axis text uses a small font size and is `#555b51` on a white background. Since we probably want to keep the font size as-is, Increasing contrast by using, say, `#33383d`, goes a long way towards making the text more readable IMHO.

![](https://user-images.githubusercontent.com/81942/104444573-3eaf5500-5598-11eb-9dbf-87b118c27753.png)

**Comment by scmmishra** [comment]
Next version of charts has CSS variables overrides that can solve these problems. You can install it using `yarn add frappe-charts@next`

Alternatively you can do css overrides, works with current version as well

```css
.chart-container .axis,
.chart-container .chart-label {
  fill: #252525;
}
```

Refer: [Charts 2.0.0.rc8](https://www.npmjs.com/package/frappe-charts/v/2.0.0-rc8)
