### ISSUE TITLE
Visualization of graphs ....

### ISSUE THREAD

**Issue by nandhinianandj** [frappe/charts#328]
#### Feature request:
   Support for visualizing and playing with graph of ideas/concepts in mind-map style.

#### Actual Behaviour
  Non existent.

#### Steps to Reproduce:
* -- An example is [Graphviz](http://graphviz.org/)
* -- Another is [Gephi](https://gephi.org/)
* -- the examples available online or companies who're close to there are [prezi](https://prezi.com/) and
* -- [roam research](https://roamresearch.com/)
* -- [mindmap](https://www.mindmeister.com/)
* -- [lucidchart](https://www.lucidchart.com)
* -- D3.js has a [dynamic tree display](https://bl.ocks.org/d3noob/8375092)

NOTE: Add a GIF/Screenshot if required.

Frappé Charts version: NA
Codepen / Codesandbox: NA

**Comment by scmmishra** [comment]
Hey, this doesn't seem relevant to what Frappe Charts aim to solve. I'm closing this issue.

**Comment by nandhinianandj** [comment]
Ah.. that's okay..... Here's a tip : it would be helpful to have this "aim" written somewhere.. I still don't understand how **this fits or not fits into the aim.**
