### ISSUE TITLE
[question] Is it possible to outline min - max value region

### ISSUE THREAD

**Issue by tsvetann** [frappe/charts#34]
Is it possible and how to outline min - max value region. I see that by default only the 0 (zero) is outlined but is it possible to achieve the same effect with min max values such as 20 (min) and 60 (max). The idea is to change color of the readings such as within range (20-60) green anything out of the range maybe red or yellow...

An example of min max range (70-90 in this example) I found on google images that i would like to achieve:

<img width="490" alt="screen shot 2017-11-03 at 18 12 45" src="https://user-images.githubusercontent.com/2565891/32386800-adaf82e0-c0c2-11e7-843a-d433a1ddc8ab.png">

The range area does not have to be filled with color can be just border outline.

Thx

**Comment by pratu16x7** [comment]
You can, by specifying an array for the `data.specific_values` prop, before passing `data` to the chart. Have updated the docs, check the 'Altitude' line for example:
![screen shot 2017-11-03 at 11 11 22 pm](https://user-images.githubusercontent.com/5196925/32388100-915b6f9e-c0ec-11e7-96b0-d27f5edfe191.png)

**Comment by tsvetann** [comment]
@pratu16x7 fantastic
