### ISSUE TITLE
Generate svg file content from this library

### ISSUE THREAD

**Issue by hydra1983** [frappe/charts#345]
Hi, is there any way to generated svg file content from this library?
Something like
```xml
<svg xmlns="http://www.w3.org/2000/svg" height="2039" width="1339" version="1.1">
<path>...
</svg>
```

**Comment by scmmishra** [comment]
You can export the [chart](https://frappe.io/charts/docs/exporting/images) as an SVG. The other option is the copy the inner html of the chart container.

**Comment by hydra1983** [comment]
Cool! Thank you.

**Comment by shridixit74** [comment]
@scmmishra is it possible to attach or copy inner html chart container over the email
