### ISSUE TITLE
[Feature request] Brush & Zoom

### ISSUE THREAD

**Issue by eeve** [frappe/charts#36]
like this

https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

https://bl.ocks.org/mbostock/f48fcdb929a620ed97877e4678ab15e6

**Comment by MartijnHarmenzon** [comment]
Any update on this feature request?

**Comment by scmmishra** [comment]
This is a desired feature, however not in the roadmap as of now. v2 is just around the corner. We might  add this to the roadmap after the release. However, most likely, we won't see this in the feature list soon
