### ISSUE TITLE
CDNJS?

### ISSUE THREAD

**Issue by arguiot** [frappe/charts#37]
Hello 👋, I'm very excited about this library 📚, do you plan to put it on CDNJS for big projects? I really like CDNJS for a lot of reasons (first of all because it's the fastest cdn), and I'm disappointed 😔 about not seeing this library on it. If you do not plan to put on it, I'll open a PR mysel if you want 😊.

**Comment by pratu16x7** [comment]
#20

**Comment by achillesrasquinha** [comment]
Closing this. Refer to @pratu16x7's link. We've got you an **unpkg**
