### ISSUE TITLE
Making a legend bar's width configurable

### ISSUE THREAD

**Issue by dsuch** [frappe/charts#376]
Hello,

thank you for creating the library, it is very nice.

I have a small feature request.

When configuring axis charts, could you please make it possible to pass in one's own value of a legend's bar size instead of always defaulting to `AXIS_LEGEND_BAR_SIZE`?

The default value of 100px is too small to fully display various longer labels in legends because they are truncated depending on the bar's width in pixels which, in turn, defaults to the constant above.

Thank you.

**Comment by scmmishra** [comment]
You can try the `spaceRatio` config. [Docs](https://frappe.io/charts/docs/basic/basic_chart#responsiveness)
