### ISSUE TITLE
trancateLegends

### ISSUE THREAD

**Issue by Timur-droid** [frappe/charts#387]
![Снимок](https://user-images.githubusercontent.com/59647050/174351813-6a161cc2-23d0-4a6a-9106-87f30c9a11ad.PNG)

How to solve the problem with long lables?

![photo_2022-06-17_22-43-07](https://user-images.githubusercontent.com/59647050/174352347-58859612-f7d9-4da6-a09a-fc6d4dd73748.jpg)

trancateLegends: true doesn't work!

**Comment by uhrjun** [comment]
Fixed in 7b5af70d80934bc622183cc48b16990cbf19e6e9
