### ISSUE TITLE
Bug: adding `lineOptions: { spline: 1 }` leads to a console error

### ISSUE THREAD

**Issue by RomkaHorokhov** [frappe/charts#396]
#### Expected Behaviour
No error in console

#### Actual Behaviour
Error in console is seen: "Error: <path> attribute d: Expected number, "…0 C 756.004,230 NaN,NaN 848.57,2…"."

#### Steps to Reproduce:
- create a line chart with `spline: 1`:
```js
{
  data: {
    labels: ["19", "20", "21", "22"],
    datasets: [ { values: [3000, 4000, 5000, 3000], name: "Smth", type: "line" } ]
  },
  height: 300,
  axisOptions: { xAxisMode: "tick", xIsSeries: true },
  colors: ["purple"],
  type: "line",
  lineOptions: {
    spline: 1
  }
}
```
- render chart
- check console

NOTE: Add a GIF/Screenshot if required.
![frappe_err](https://user-images.githubusercontent.com/102025939/189619465-cc6efba8-3447-48f3-bf94-6aeec6e8ed75.png)
![frappe_err_details](https://user-images.githubusercontent.com/102025939/189627400-0d66cfdc-c86c-462e-bbd0-907fda323be7.png)
The issue seems to be with the pre-last `C` in svg's path as shown on the last screenshot

Frappé Charts version: 1.6.2
Codepen / Codesandbox: https://codepen.io/nerveclasp/pen/mdLEamy

**Comment by uhrjun** [comment]
SVG error seems to only be logged in Chromium (not anything of note its just interesting). Seems to have been caused by the `ResizeObserver` in commit 12533f3b376328a8437109977910c8f2041572e5. Which is being looked at to revert. Thanks for reporting the issue.
