### ISSUE TITLE
[Feature request] Spline chart functionality

### ISSUE THREAD

**Issue by sweetyams** [frappe/charts#4]
The library looks great! Do you have plans on supporting spline and areaspline charts?

There is a great doc with a variety of options for types of [line interpolations:](http://www.d3noob.org/2013/01/smoothing-out-lines-in-d3js.html)

**Comment by achillesrasquinha** [comment]
This is a good idea. Spline is something that is seriously needed.

**Comment by pratu16x7** [comment]
@sweetyams We'd love to! We're currently working on making these as easy to use as we can, as well as contribution guidelines. Charts sure have plenty of use cases, so this'll help people to add stuff they wish to :)

**Comment by nniclas** [comment]
I added spline functionality to a line type chart, it is also supported with area (regionFill).
It can be toggled with: lineOptions { spline: true }.

see fork: https://github.com/nniclas/charts.git
