### ISSUE TITLE
Support passing in parent as dom element rather than only a string id.

### ISSUE THREAD

**Issue by bahrus** [frappe/charts#40]
I'm working on a web component wrapper around this library.  If you could support this option, life would be much easier.

**Comment by pratu16x7** [comment]
Yep, we do, thanks to @tobiaslins 
https://github.com/frappe/charts/blob/master/src/scripts/charts/BaseChart.js#L25

Have updated the docs. Cheers!

**Comment by bahrus** [comment]
I guess it hasn't published to npm yet?  I was referencing https://unpkg.com/frappe-charts@0.0.3/dist/frappe-charts.min.iife.js , and it still seems to have the old code.

**Comment by pratu16x7** [comment]
Yeah we plan on publishing in some time, some refactoring on the way.

**Comment by pratu16x7** [comment]
Published, feel free to reopen in case of issues.
