### ISSUE TITLE
Multi-axis support

### ISSUE THREAD

**Issue by rororo** [frappe/charts#41]
##### Multi-axis support for line chat.
 e.g. chart.js
http://www.chartjs.org/samples/latest/charts/line/multi-axis.html

**Comment by raygerrard** [comment]
I am also looking for multi-axis support.

It would be good to be able to add 2 or more but also to have the ability for the same axis to be used for multiple data sets.

Also to be able to specify the position to the left or right of the chart with an optional label.

**Comment by pratu16x7** [comment]
@raygerrard 
`add 2 or more`
GitHub and Chartjs feature 2 axes graphs, I assumed multiple axis to mean 2 axes at opposite ends. Not sure how you would add more than 2; could you elaborate?

`ability for the same axis to be used for multiple data sets`
Seems like that is already present in the current functionality in the case of multiple datasets.

`Also to be able to specify the position to the left or right of the chart with an optional label.`
This also seems that once we place and axis at the left, other at the right, there won't be any space for more than 2 at a time.

**Comment by raygerrard** [comment]
@pratu16x7 example http://demos.telerik.com/kendo-ui/bar-charts/multiple-axes

**Comment by scmmishra** [comment]
v1 added support for this. Closing dormant thread.
