### ISSUE TITLE
Angular directive issue ?

### ISSUE THREAD

**Issue by iamkdev** [frappe/charts#42]
https://github.com/frappe/charts/blob/bb2aeaa7775994f6021d1b56942d27882be8af02/src/scripts/charts/BaseChart.js#L25

I am trying to create Angular 2+ directive. As I have access to the element in the directive `this.el.nativeElement`, I want to use it as parent. But its not working. Only works when i set via attribute like id, class etc.

**Comment by pratu16x7** [comment]
Any console errors?
Not an expert in Angular, but does `this.el.nativeElement` mean a dom element?

**Comment by achillesrasquinha** [comment]
Hi @iamkdev, not an angular person here but do you think this is related to #2 ?

Ensuring you don't spend time while there comes an update.

**Comment by iamkdev** [comment]
Thanks for the awesome chart @pratu16x7.

@achillesrasquinha, the output of `this.el.nativeElement` and `document.querySelector('#some-id')` same. i.e. `<div id="some-id"></div>`.

**Comment by pratu16x7** [comment]
Published, updated docs, feel free to reopen in case of issues. Cheers!
