### ISSUE TITLE
Maybe 'charts' needs a tool to get json data from server, does the WisdomTool REST Client meet the requirement: https://github.com/wisdomtool/rest-client ？ 

### ISSUE THREAD

**Issue by ma-spring** [frappe/charts#46]
[WisdomTool REST Client](https://github.com/wisdomtool/rest-client) supports automated testing RESTful API and automatically generating RESTful API documentation.

It may help this project to get json data from server.

**Comment by achillesrasquinha** [comment]
Sure, you could pretty much use any `HTTP` lib out there to your render charts. Not sure whether we'd like to build an API within `Charts` itself.
