### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by tabuna** [frappe/charts#47]
Hi, how can I set the default colors?
I have a color scheme that is used in the project, it's not very convenient for me to override the color of the meaning.

Is it possible to establish that the colors of the graphs will be taken from my polytyra. (Order is not important)

**Comment by pratu16x7** [comment]
We only support a predefined set as of now, the `color` property will have to be one of them:
![screen shot 2017-11-07 at 2 09 30 am](https://user-images.githubusercontent.com/5196925/32462814-bce32118-c360-11e7-82c7-cbd4e37a353c.png)

If unspecified, they will be set by default in this order. We are planning to incorporate hex codes soon.

**Comment by pratu16x7** [comment]
Please check updates about this at https://github.com/frappe/charts/issues/23. Closing here.
