### ISSUE TITLE
Dynamic minimum Y values 

### ISSUE THREAD

**Issue by dannyk660** [frappe/charts#48]
I have a line chart where the minimum Y value is 10,000 and the maximum Y value is 13,000. It would be awesome if frappe automatically adjusted the Y values accordingly. It currently always starts at 0, creating a lot of empty space, and an uninteresting chart. 

Thanks!

**Comment by pratu16x7** [comment]
@dannyk660 Zero baselines are intentional, every data point on the graph is meant to be at its absolute (as opposed to relative) value: http://www.storytellingwithdata.com/blog/2012/09/bar-charts-must-have-zero-baseline

But we'd be happy to checkout exceptions (as visuals/use-cases) to this rule :)

**Comment by dannyk660** [comment]
Sure, thanks for your response! Here's an example of what I'm looking at: 

https://imgur.com/FkQSYjt

By starting at zero, it's pretty hard to discern any variations in the data, since all the action happens from 13k to 19k. 

Thanks again!

**Comment by pratu16x7** [comment]
Cool! Yeah, looks like this could use a more dynamic range. We'll put this right up there with the tiny fractions feature. Cheers!

**Comment by pratu16x7** [comment]
So here's the update.

Line charts now have a dynamic minimum value🎉; check them out on the demo! (The set in the screen below has a 10-70 range)
![screen shot 2017-11-14 at 3 15 18 am](https://user-images.githubusercontent.com/5196925/32755741-b58571a4-c8fc-11e7-85bb-b8d283bc5d55.png)

It also works on all negatives
![screen shot 2017-11-14 at 3 34 32 am](https://user-images.githubusercontent.com/5196925/32755794-f346bb1a-c8fc-11e7-8f93-f54ebd9af38c.png)

Anyone interested can check `intervals.js` for the new generic intervalling ;) We also support fractions.

**Comment by pratu16x7** [comment]
Do reopen in case you find any issues. Closing as fulfilled.

**Comment by trimoda** [comment]
It's still not adjusting for me. For example, data between 0.29 and 0.31, y axis has a range between 0.20 and 0.40. Thank you.

**Comment by Jossnaz** [comment]
@pratu16x7 is there a way to disable this feature?
