### ISSUE TITLE
Format tooltip value

### ISSUE THREAD

**Issue by vitornogueira** [frappe/charts#49]
Is it possible to format the value displayed in the tooltip?

e.g. **89**  >  **$ 89.00**

![screenshot from 2017-11-07 01-06-13](https://user-images.githubusercontent.com/928406/32475319-409ed5dc-c358-11e7-9e3c-914a9973a408.png)

**Comment by pratu16x7** [comment]
@vitornogueira Wouldn't that be cool? :) We actually included that as a `formatted` property in every `dataset` in addition to the `values` supplied. But of course, it would make sense if you could just define one format for all datasets, outside the `datasets` array.
Hang tight, we'll be doing a release over the weekend 😃

**Comment by pratu16x7** [comment]
We've released this; `format_tooltip_x` and `format_tooltip_y` now do the job. You can check them out on the website. Closing.

**Comment by vitornogueira** [comment]
Awesome! Thanks :smile:
