### ISSUE TITLE
it has a k line chart?

### ISSUE THREAD

**Issue by fantasthu** [frappe/charts#50]
it has a k line chart

**Comment by pratu16x7** [comment]
Not yet. What does it look like?

**Comment by fantasthu** [comment]
stock k line,can you add it?thank you

**Comment by pratu16x7** [comment]
Please provide more details for it to be a feature request. Closing, do feel free to reopen :)

**Comment by fantasthu** [comment]
like this
![image](https://user-images.githubusercontent.com/9922079/32821655-7fa15d1e-ca0f-11e7-8e7d-2574df0ccb1b.png)

**Comment by pratu16x7** [comment]
Not an expert on these :) If anyone could help with some insights that'd be great.

**Comment by taohex** [comment]
I need this, too. It's useful in stock. Every day has a green bar or red bar.

**Comment by scmmishra** [comment]
Closing dormant issue.
