### ISSUE TITLE
[Question] is it possible to display scatter chart as time series

### ISSUE THREAD

**Issue by tsvetann** [frappe/charts#55]
Is it possible somehow to display scatter chart more as time series. The effect I would like to achieve is to distribute measurements in a more realistic visual way rather than stacking them on top of each other as it is in the example.

Just to clarify:
Currently, in the example if you have 5 values within the same hour they are displayed stacked on top of each other. What I would like is to display them according to the exact minute.

Thx.

**Comment by pratu16x7** [comment]
That would mean different X values for every dataset. Right now, X can only take a single values set for all of them.
