### ISSUE TITLE
Is this only a global or does it work with webpack/browserify?

### ISSUE THREAD

**Issue by davidguttman** [frappe/charts#6]
Don't see anything about `require('frappe-charts')` or `import Chart from 'frappe-charts'`

Is the only way to use this to have a script tag on the page and have a global `Chart` object?

**Comment by achillesrasquinha** [comment]
Something like
```
frappe.Chart
```
?

Yeah, we're having it published.

**Comment by costpermille** [comment]
I think david means exporting as in proper ES6 module, so there isn't even a hardcoded `frappe.Chart` to speak of, not just namespacing it into a frappe global?

**Comment by achillesrasquinha** [comment]
We have it published on npm right now.

**Comment by egoist** [comment]
I think it's as easy as changing 2 or 3 lines in rollup.config.js to make it output UMD bundle

**Comment by gwillz** [comment]
`dist/frappe-charts.min.js` _does_ exist though. Probably just a NODE_ENV production flag thing during the `npm pack` process.

Alternatively, `import Chart from 'frappe-charts/src/scripts/charts';` does work if you're using webpack with `less-loader`.

**Comment by eeve** [comment]
```js
import Chart from 'frappe-charts/dist/frappe-charts.min.esm'
```

**Comment by pratu16x7** [comment]
So we've made it importable. Try it out at https://npm.runkit.com/frappe-charts. 

![screen shot 2017-11-04 at 3 10 13 pm](https://user-images.githubusercontent.com/5196925/32404565-be83d796-c177-11e7-9d07-a0fd5f1a2f97.png)

We will be working on the namespacing next.

**Comment by pratu16x7** [comment]
Looks like this is no longer relevant. Closing for now.
