### ISSUE TITLE
[Feature Request] Specific x values

### ISSUE THREAD

**Issue by tristansokol** [frappe/charts#63]
I'm using day/dates on the x axis and I'd like to indicate weekends some how. This could be done with some kind of axis options, but since specific y values exist, It seems like specific x would be the implementation path. 

Here is what I'd kind of like: 
![screen shot 2017-11-08 at 7 11 24 pm](https://user-images.githubusercontent.com/867661/32586721-313b640e-c4b9-11e7-94e5-aa073551db16.jpg)

Happy to work on a PR if someone could comment if it would be accepted, and maybe a basic outline of implementation? I'm guessing copying the specific y code wouldn't be too hard.

**Comment by pratu16x7** [comment]
I agree the implementation could use the `specific_y` pattern; the`make_x_line()` in `draw.js` will come in handy. However, it can't as of yet draw coloured lines.

The range bars would need to be implemented though.

**Comment by pratu16x7** [comment]
Just noticed #5 is basically this. Leaving a link to this issue and closing; feel free to continue the conversation there.
