### ISSUE TITLE
[Feature request] Stacked Bar Charts

### ISSUE THREAD

**Issue by joepa37** [frappe/charts#64]
Thanks for awesome frappe charts!

C3 library support group columns in bar charts using:

`groups: [
    ['Writing','Reading', 'Understanding']
],`

Would be nice to be able to do that.
Here is an example using c3: [https://jsfiddle.net/joepa37/xg3zx2m4/](https://jsfiddle.net/joepa37/xg3zx2m4/)

Preview:
![image](https://user-images.githubusercontent.com/15274305/32588515-cdb00892-c4d4-11e7-86ee-3879c3ee9fec.png)

**Comment by blakeperdue** [comment]
+1 would love to have stacked bar charts as it's a common chart type and I would benefit from it.

**Comment by frlinw** [comment]
work in progress on `develop` branch
https://github.com/frappe/charts/commit/df158851354ce79c46bd1c8deb2f527f857a5d88

**Comment by pratu16x7** [comment]
Supported as of now, please refer #132 and report any issues you find in the feature.

**Comment by Tektician** [comment]
I gave up waiting for this on frappe chart and just used google chart, The following script before your page will allow you to use google chart flawlessly.

import_css_and_js = function() {
frappe.require("assets/js/loader.js");  **<-- download and place the google charts js file locally.**
}
import_css_and_js();
