### ISSUE TITLE
[Tests] for charts

### ISSUE THREAD

**Issue by pratu16x7** [frappe/charts#7]

**Comment by tom-sherman** [comment]
@pratu16x7 I'd like to have a crack at this. I was going to go with Jasmine, but do you have any preference on testing framework?

**Comment by harunurhan** [comment]
@tom-sherman I am not a collaborator but I'd suggest you take a look at https://github.com/facebook/jest

I find it unbelievable that the project of this size, with 10k stars and 3k of monthly downloads doesn't have a single test.
