### ISSUE TITLE
Long tail of decimal value

### ISSUE THREAD

**Issue by thucnc** [frappe/charts#79]
#### Expected Behaviour
The decimal number in y axis should be rounded to 2 digits
#### Actual Behaviour
The decimal number has a long tail in y axis.
#### Steps to Reproduce:
An array of 2 digits decimal numbers for datasets
*
![screen shot 2017-11-21 at 7 48 18 pm](https://user-images.githubusercontent.com/2088055/33073531-c1367cce-cef5-11e7-931c-8cc1b74db2fe.png)

Frappé Charts version: 0.07

**Comment by scmmishra** [comment]
This is [fixed](https://github.com/frappe/charts/pull/288)
