### ISSUE TITLE
Strange Y line value 

### ISSUE THREAD

**Issue by wtser** [frappe/charts#83]
when using some special value, will cause strange render

![image](https://user-images.githubusercontent.com/2093743/33217246-0f24f55e-d172-11e7-9332-08c4d7a3dc05.png)

![image](https://user-images.githubusercontent.com/2093743/33217207-e9c1317e-d171-11e7-97a1-ff4cddccf934.png)

**Comment by hkfoster** [comment]
Same issue here.

![image](https://user-images.githubusercontent.com/1379387/33624556-621c926c-d9ba-11e7-8fd2-ac2140800fd1.png)

```
<text class="y-value-text" x="-9" y="0" dy=".32em">0.30000000000000004</text>
```

```
{  
   "title":"Error rate",
   "values":[  
      "0.16",
      "0.26",
      "0.10",
      "0.15",
      "0.10",
      "0.22",
      "0.00",
      "0.16",
      "0.12",
      "0.12",
      "0.17",
      "0.11",
      "0.06",
      "0.08",
      "0.12",
      "0.23",
      "0.19",
      "0.20",
      "0.22",
      "0.16",
      "0.08",
      "0.02",
      "0.14",
      "0.08",
      "0.07",
      "0.06",
      "0.21",
      "0.12",
      "0.09",
      "0.17",
      "0.14",
      "0.05",
      "0.17",
      "0.12",
      "0.08",
      "0.11",
      "0.10",
      "0.11",
      "0.17",
      "0.12",
      "0.08",
      "0.04",
      "0.09",
      "0.00",
      "0.09",
      "0.19",
      "0.00",
      "0.16",
      "0.00",
      "0.00"
   ]
}
```

**Comment by prolakeindia** [comment]
![image](https://user-images.githubusercontent.com/22707022/49008595-31eefd80-f194-11e8-819f-9250be3bb894.png)

Same issue seen. In Y axis value 00000000004 is seen. Is this issue resolved?

**Comment by trimoda** [comment]
Any workaround/solution for this?
