### ISSUE TITLE
When using pie chart display problems.

### ISSUE THREAD

**Issue by fddi** [frappe/charts#84]
using pie chart display problems,High proportion of the data is not displayed
![1](https://user-images.githubusercontent.com/6425507/33255148-27fa66e2-d387-11e7-82c1-10bf03919d52.png)

**Comment by digitlz** [comment]
Got the same problem. With two or three not-so-small parts and one large part it looks even worse. Seems to be an issue with displaying the large portion within the pie chart when there are minor parts.

![bildschirmfoto 2017-11-27 um 11 32 21](https://user-images.githubusercontent.com/34026307/33262527-d5ab45e8-d366-11e7-885e-0199255145bc.png)
![bildschirmfoto 2017-11-27 um 11 36 40](https://user-images.githubusercontent.com/34026307/33262665-56b034aa-d367-11e7-8aab-75589d19411f.png)
```typescript
const pieData = {
  labels: ['test1', 'test2', 'test3', 'test4'],
  datasets: [
    {values: [50, 300, 40, 30]}
  ]
};

const chart = new Chart({
  parent: '#chart',
  data: pieData,
  type: 'pie',
  height: 400
});
```

**Comment by digitlz** [comment]
[This should be the line](https://github.com/frappe/charts/blob/master/src/js/charts/PieChart.js#L70) causing the issue. The [path string](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) seems to calculate the curvature into the wrong direction.

- M **(Move To)** centerX centerY
- L **(Line To)** centerX+startPosition.x centerY+startPosition.y
- A **(Arc)** radius radius 0 0 1 centerX+endPosition.x centerY+endPosition.y z

**Comment by alx-** [comment]
You can fix it by setting large-arc-flag argument of A command.

I did a quick fix [here](https://github.com/alx-/charts/blob/tests/src/js/charts/PieChart.js).

It messes up the animation though, don't know a fix for that.

**Comment by electricalessence** [comment]
Hello digitlz , for what I've seen the pie chart data has to be percentage so the circle can be completed, maybe the data values can go into labels.

**Comment by scmmishra** [comment]
The issue has been fixed in the recent release. https://github.com/frappe/charts/pull/181
