### ISSUE TITLE
[UPDATE] Development Progress

### ISSUE THREAD

**Issue by pratu16x7** [frappe/charts#93]
So we've been receiving a lot of feature requests lately. I discovered however, that the components in the current implementation aren’t sufficiently decoupled to allow for easy extensibility. Here’s what  currently happens (as we'd expect from a functional program):
**Step 1**: `make_components()` makes groups for every component required.
**Step 2**: `draw()` renders the svgs for all them
**Step 3**: At some further point in time when values are updated, `run_animation()` follows a similar pattern.

This came out of the project's origins and incremental feature updates. But UI in general is better describable with OOP. 
I've been trying out some restructuring; we could instead go for some initial registering for any chart component like so (`ChartComponent` implements a component's properties):
![screen shot 2017-12-08 at 10 15 43 pm copy](https://user-images.githubusercontent.com/5196925/33776670-234536ec-dc68-11e7-868e-f64c2905c8be.png)

Then `BaseChart` could just follow a life-cycle. That’d mean every component will know what it has to do, without the chart needing to bother:
![screen shot 2017-12-08 at 10 20 03 pm](https://user-images.githubusercontent.com/5196925/33776673-261300ac-dc68-11e7-939c-916519452e5a.png)

Here's some of the stuff I was able to add without much effort (more on the way):
#### Mixed charts:
![screen shot 2017-12-05 at 5 19 02 am](https://user-images.githubusercontent.com/5196925/33776801-8d466f3e-dc68-11e7-80eb-74b5a27f8254.png)

#### Multiple Axis:
![screen shot 2017-12-08 at 9 55 42 pm](https://user-images.githubusercontent.com/5196925/33776860-c6933f56-dc68-11e7-9545-dd61f616ef23.png)

Most of the logic has now been transferred to utils, and no chart has more than 200-250 LOCs. As we look forward to test coverage, this’ll help the project to have predictable (and less) tests. And the contribution guidelines to have a well-defined code structure.

_These will constitute v0.1.0, which will be released by the end of this month._

Apologies for the delay in updates, but I feel this detour was needed before any more feature additions. Haven't been able to catch up with the current issues and pull requests; will go ahead release a first cut with most of the fixes and merges by the in the coming week, tagging the in-progress ones in the meantime. Thanks for your patience :)

Will keep posting updates, check this space. You can track the progress on the `develop` branch :D

**Comment by frlinw** [comment]
0.1.0 seems to be nice!
I wonder if the api will have `format_tooltip_*` for each axis ?

**Comment by tomcon** [comment]
@pratu16x7 am a little concerned, It's now Jan 18th, nothing for 16 days on dev branch + 6 weeks ago:

> These will constitute v0.1.0, which will be released by the end of this month.

Can we have an update where things are or when v0.1 might be released please? Many thanks

**Comment by srkunze** [comment]
Some updates here?

**Comment by tomcon** [comment]
@pratu16x7 
sorry, but why promise things and then not keep your word (or at least communicate any delays/problems)? I spent a *lot* of time converting to Frappe charts and expected this to be an actively developed project as per your comments, but it is not, it is pretty much dead. 
Thank you for open sourcing it, it's truly appreciated but maybe you shouldn't have.

**Comment by tobscure** [comment]
Looks like active development *is* still ongoing in the [`develop` branch](https://github.com/frappe/charts/commits/develop). But a progress update would be greatly appreciated 😊

**Comment by tomcon** [comment]
I did see that before I posted earlier - 
but between 8th Dec 2017 and 16th Feb 2018 ... 
zero communication and pretty much zero commits
I very much, _greatly_ in fact, appreciate your work but please communicate better so we know where you are and whether this is a project to stay with or abandon. Thanks

**Comment by pratu16x7** [comment]
Greetings all.

It is a pity this didn't go quite as planned, and I had to abandon the earlier pure OO model for a functional approach at the micro-component(`drawBar`, `drawLine` etc) level, leaving the component approach for macros (the `axis` component and so on) that update/animate collectively. Looks like this works fairly well, and I'm working on porting the aggregation charts (Pie/Percentage) in a similar fashion over the weekend (reflected on `develop` lately). This was far too many threads I have ever handled, and I am happy that it came about in the end.

Apologies for the less than active maintenance of an appreciated project, I admit it could have taken a lot less time. I would say I would be shipping 1.0.0 beta on Monday, but it would probably be better to ship first and announce later. This sure would close many issues as it would probably create, along with some existing PRs. Thank you all for your support on it :)

**Comment by tomcon** [comment]
@pratu16x7 Thank you very much for the update. 
And also thank you very much for your fine work.

**Comment by pratu16x7** [comment]
@GrosSacASac I agree. Ideally, the generated chart element should be purely SVG, making it altogether portable. We do have plans to make these easily importable, so yes that would probably be the first step to do it.
