### ISSUE TITLE
Destroy the existing chart

### ISSUE THREAD

**Issue by lanjingling0510** [frappe/charts#97]
#### Expected Behaviour
Destroy the existing chart.
#### Steps to Reproduce:
*

NOTE: Add a GIF/Screenshot if required.

Frappé Charts version:

**Comment by lanjingling0510** [comment]
I do not know how to destroy a chart.
```javascript
	bind_window_events() {
		window.addEventListener('resize', () => this.refresh());
		window.addEventListener('orientationchange', () => this.refresh());
	}
```
Events on the window can not be canceled.

**Comment by brandonparsons** [comment]
Commenting so I get notified of any hints here....

**Comment by pratu16x7** [comment]
@lanjingling0510 Not sure of how else we could handle events like these, could you guide on it?

**Comment by frlinw** [comment]
https://github.com/frappe/charts/blob/master/dist/frappe-charts.esm.js#L1192
You can't remove a listener if you pass an anonymous function to it
Do something like this instead maybe
```
listenToMe () {
  this.draw(true)
}

configure () {
  window.addEventListener('resize', this.listenToMe);
  window.addEventListener('orientationchange', this.listenToMe);
}

destroy () {
  window.removeEventListener('resize', this.listenToMe);
  window.removeEventListener('orientationchange', this.listenToMe);
}
```

**Comment by t47io** [comment]
I hope the maintainers can pass the opened PRs, e.g. https://github.com/frappe/charts/pull/94 which deals with this issue. It has been there for 3 months.

**Comment by frlinw** [comment]
`unbindWindowEvents` is meaningless for the public API & not future proof, a `destroy` method which call `unbindWindowEvents` would be better

**Comment by t47io** [comment]
@pratu16x7 can you fix line 94 and 103 please? it should be the same way as line 93 and 102:
https://github.com/frappe/charts/blob/a47a4d0eb786de169a05fa1b526ce07c43b3b6b9/src/js/charts/BaseChart.js#L92-L94

**Comment by t47io** [comment]
Also to point out that the current implementation only works when there is 1 chart in the DOM. If there are 2, only 1 can successfully unbind. The fix is to associate `BOUND_DRAW_FN` to `this`, i.e.:
```
this.BOUND_DRAW_FN = this.boundDrawFn.bind(this);
window.addEventListener('resize', this.BOUND_DRAW_FN);
window.removeEventListener('resize', this.BOUND_DRAW_FN);
```

This bug is hard to tell b/c `removeEventListener` can silently fail, but you can reproduce it following https://stackoverflow.com/questions/34079323/how-do-i-know-that-removeeventlistener-was-successful.

**Comment by t47io** [comment]
@pratu16x7 I can make a PR for the above issue if you'd prefer.

**Comment by pratu16x7** [comment]
@t47io Please do :) Will make sure to merge it asap.

**Comment by GrosSacASac** [comment]
Can be closed
https://github.com/frappe/charts/pull/164
